spring:
  config:
    import: optional:classpath:identityhub-conf.yml
  application:
    name: identity-hub
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration